import elementary from '@quarkly/elementary';

export default elementary.div(
  {
    name: 'Flex',
    styles: [
      'display',
      'height',
      'minHeight',
      'maxHeight',
      'width',
      'minWidth',
      'maxWidth',
      'padding',
      'paddingTop',
      'paddingRight',
      'paddingBottom',
      'paddingLeft',
      'paddingX',
      'paddingY',
      'margin',
      'marginTop',
      'marginRight',
      'marginBottom',
      'marginLeft',
      'marginX',
      'marginY',
      'alignItems',
      'alignContent',
      'justifyItems',
      'justifyContent',
      'flexWrap',
      'flexBasis',
      'flexDirection',
      'flex',
      'order',
      'justifySelf',
      'alignSelf',
      'zIndex',
    ],
    variant: 'flexs',
  },
  {
    display: 'flex',
  },
);
